---
- hosts: db
  tasks:
  - name: Install the Python MySQL Module
    apt:
     name: python-mysqldb
     state: installed
  - name: Update Repository
    apt: 
     update_cache: yes
    become: yes
  - name: Install MySQL 
    apt: 
     name: mysql-server
     state: installed
  - name: Start MySQL Service
    service:
     name: mysql
     state: started
     enabled: yes
  - name: Create a MySQL database
    mysql_db:
       name: wordpress_db
       state: present
       login_user: dungnt
       login_password: abc
    become: yes
    notify: restart mysql     
    handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
