---
- hosts: web
  tasks:
  - name: Update Repository
    apt: 
     update_cache: yes
    become: yes
  - name: Install MySQL-Client
    apt:
     name: mysql-client
  - name: Install apache, php
    apt: 
     pkg: 
     - apache2
     - php
     - php-curl 
     - php-gd 
     - php-mbstring
     - php-xml 
     - php-xmlrpc   
     - php-soap 
     - php-intl 
     - php-zip
     - libapache2-mod-php
     - php-mysql
     - php7.2-fpm
  - name: Start apache service
    service:
     name: apache2
     state: started
     enabled: yes
  - name: Get wordpress from source
    get_url:
     url: http://wordpress.org/latest.tar.gz
     dest: /var/www/lastest.tar.gz
  - name: Uncompress wordpress tar ball
    unarchive:
     remote_src: yes 
     src: /var/www/lastest.tar.gz
     dest: /var/www/
  - name: Rename directory
    command: "mv /var/www/wordpress /var/www/dungnt.com"
  - name: Rename file
    command: "mv /var/www/dungnt.com/wp-config-sample.php /var/www/dungnt.com/wp-config-sample.php.bak"
  - name: Change owner and mode
    file:
       path: /var/www/dungnt.com
       owner: www-data
       group: www-data
       mode: '0755'
       recurse: yes
       state: directory
  - name: Enable PHP-FPM 
    command: a2enconf php7.2-fpm && a2enmod proxy_fcgi setenvif
  - name: Copy a created wp-config.php and backup it
    template:
       src: /etc/ansible/wp-config.php
       dest: /var/www/dungnt.com/wp-config.php
       backup: yes
  - name: Copy an edited default configuration of Apache and backup it
    template:
       src: /etc/ansible/000-default.conf
       dest: /etc/apache2/sites-available/000-default.conf
       backup: yes
    notify: restart apache
  - name: Add ha entry in /etc/hosts
    become: yes
    become_user: root
    shell: echo "103.107.182.185 ha" >> /etc/hosts
  - name: Add web server 1 entry in its /etc/hosts when the ip is 103.107.182.45
    become: yes
    become_user: root
    shell: echo "103.107.182.45 dungnt.com" >> /etc/hosts
    when: "'web1' in inventory_hostname"
  - name: Add web server 2 entry in its /etc/hosts when the ip is 103.107.182.199
    become: yes
    become_user: root
    shell: echo "103.107.182.199 dungnt.com" >> /etc/hosts
    when: "'web2' in inventory_hostname"
  handlers:
     - name: restart apache
       service: 
        name: apache2
        state: restarted
